apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.azure.images.gif2t.name }}-configmap
data:
  TELEGRAM_DISABLE_NOTIFICATION: {{ quote .Values.config.TELEGRAM_DISABLE_NOTIFICATION }} #default=True, set it to false if you want add notification to the messages
  FFMPEG_FPS: {{ quote .Values.config.FFMPEG_FPS }} #default=10
  FFMPEG_WIDTH: {{ quote .Values.config.FFMPEG_WIDTH }} # default=320, height is calculated from the width
  FFMEG_NOAUDIO: {{ quote .Values.config.FFMPEG_NOAUDIO }} #default=True, set it to false if you want to send audio
  AzureWebJobsStorage: {{ required "config.AzureWebJobsStorage is required" .Values.config.AzureWebJobsStorage }}
  CameraDropFilesStorage: {{ required "config.CameraDropFilesStorage is required" .Values.config.CameraDropFilesStorage }}
  TELEGRAM_API_KEY: {{ .Values.config.TELEGRAM_API_KEY | required "config.TELEGRAM_API_KEY is required" | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.config.TELEGRAM_CHAT_ID | required "config.TELEGRAM_CHAT_ID is required" | quote }}