# create a pod with a single container running the busybox image
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: gif2t
  name: gif2t
spec:
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.version }}
    name: {{ .Release.Name }}-{{ .Values.image.name }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    env:
    - name: AzureFunctionsJobHost__functions__0
      value: FromBlob
    envFrom:
    - configMapRef:
        name: {{ .Release.Name }}-{{ .Values.image.name }}-configmap
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 240
      httpGet:
        path: /
        port: 80
        scheme: HTTP
    startupProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 240
      httpGet:
        path: /
        port: 80
        scheme: HTTP
